# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  linux:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.0', '8.0', '10.0' ]

    steps:
    # - name: Install dependencies
    #   run: sudo apt install -y mono-devel
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      id: stepid
      with:
        dotnet-version: ${{ matrix.dotnet }}
    # By default, tests will be executed under the latest installed version!
    - name: Create temporary global.json
      run: echo '{"sdk":{"version":"${{steps.stepid.outputs.dotnet-version}}"}}' > ./global.json
    - name: Restore packages
      run: dotnet restore -p:TargetFrameworks="net${{ matrix.dotnet }}" -p:LangVersion="latest"
    - name: Build solution
      run: dotnet build --no-restore --configuration Release -p:TargetFrameworks="net${{ matrix.dotnet }}" -p:LangVersion="latest" --verbosity normal
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal -p:TargetFrameworks="net${{ matrix.dotnet }}" -p:LangVersion="latest"

  windows:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet: [ '6.0', '8.0', '10.0' ]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      id: stepid
      with:
        dotnet-version: ${{ matrix.dotnet }}
    # By default, tests will be executed under the latest installed version!
    - name: Create temporary global.json
      run: echo '{"sdk":{"version":"${{steps.stepid.outputs.dotnet-version}}"}}' > ./global.json
    - name: Restore packages
      run: dotnet restore -p:TargetFrameworks="net${{ matrix.dotnet }}" -p:LangVersion="latest"
    - name: Build solution
      run: dotnet build --no-restore --configuration Release -p:TargetFrameworks="net${{ matrix.dotnet }}" -p:LangVersion="latest" --verbosity normal
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal -p:TargetFrameworks="net${{ matrix.dotnet }}" -p:LangVersion="latest"
